version: "3.5"

services:
  test_my_chatbot_dashboard_staging:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: staging.dashboard.test-my-chatbot.com
    restart: on-failure
    environment:
      - NODE_ENV=staging
    volumes:
       - ${REPO_PATH}/test-my-chatbot:/src
    # port make it available outside the container AND server
    ports:
      - "3006:8080"
    command: bash -c "npm run prod"
    networks:
      - default

networks:
  default:
    external:
      name: webproxy
