version: "3.5"

services:
  test_my_chatbot_dashboard_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: dashboard.test-my-chatbot.com
    restart: on-failure
    environment:
      - VIRTUAL_HOST=dashboard.test-my-chatbot.com
      - LETSENCRYPT_HOST=dashboard.test-my-chatbot.com
      - LETSENCRYPT_EMAIL=herve.tchikladze@epitech.eu
      - NODE_ENV=production
      - HOST=https://dashboard.test-my-chatbot.com
    volumes:
       - ${REPO_PATH}/test-my-chatbot:/src
    # port make it available outside the container AND server
    ports:
      - "3007:8080"
    command: bash -c "npm install && npm run build && npm run prod"
    networks:
      - default

networks:
  default:
    external:
      name: webproxy
