export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
// export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//---------------------------------------------------------------------

export const LOAD_CUSTOMERS_REQUEST = "LOAD_CUSTOMERS_REQUEST";
export const LOAD_CUSTOMERS_SUCCESS = "LOAD_CUSTOMERS_SUCCESS";
export const LOAD_CUSTOMERS_FAILURE = "LOAD_CUSTOMERS_FAILURE";

export const GET_CUSTOMER_REQUEST = "GET_CUSTOMER_REQUEST";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_FAILURE = "GET_CUSTOMER_FAILURE";

export const NEW_CUSTOMER_REQUEST = "NEW_CUSTOMER_REQUEST";

export const UPDATE_CUSTOMER_REQUEST = "UPDATE_CUSTOMER_REQUEST";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAILURE = "UPDATE_CUSTOMER_FAILURE";

export const ADD_CUSTOMER_REQUEST = "ADD_CUSTOMER_REQUEST";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_CUSTOMER_FAILURE = "ADD_CUSTOMER_FAILURE";

export const DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE";

//---------------------------------------------------------------------

export const LOAD_ORDERS_REQUEST = "LOAD_ORDERS_REQUEST";
export const LOAD_ORDERS_SUCCESS = "LOAD_ORDERS_SUCCESS";
export const LOAD_ORDERS_FAILURE = "LOAD_ORDERS_FAILURE";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILURE = "GET_ORDER_FAILURE";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAILURE = "UPDATE_ORDER_FAILURE";

export const NEW_ORDER_REQUEST = "NEW_ORDER_REQUEST";

export const ADD_ORDER_REQUEST = "ADD_ORDER_REQUEST";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILURE = "ADD_ORDER_FAILURE";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE";

//---------------------------------------------------------------------

export const LOAD_CATEGORYS_REQUEST = "LOAD_CATEGORYS_REQUEST";
export const LOAD_CATEGORYS_SUCCESS = "LOAD_CATEGORYS_SUCCESS";
export const LOAD_CATEGORYS_FAILURE = "LOAD_CATEGORYS_FAILURE";

export const LOAD_PRODUCTS_REQUEST = "LOAD_PRODUCTS_REQUEST";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_FAILURE = "LOAD_PRODUCTS_FAILURE";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

//---------------------------------------------------------------------

export const REQUEST_GET_COMPANIES = "REQUEST_GET_COMPANIES";
export const RECEIVE_GET_COMPANIES = "RECEIVE_GET_COMPANIES";
export const INVALIDATE_GET_COMPANIES = "INVALIDATE_GET_COMPANIES";
export const REQUEST_POST_COMPANIES = "REQUEST_POST_COMPANIES";
export const RECEIVE_POST_COMPANIES = "RECEIVE_POST_COMPANIES";
export const INVALIDATE_POST_COMPANIES = "INVALIDATE_POST_COMPANIES";
export const REQUEST_PATCH_COMPANIES = "REQUEST_PATCH_COMPANIES";
export const RECEIVE_PATCH_COMPANIES = "RECEIVE_PATCH_COMPANIES";
export const INVALIDATE_PATCH_COMPANIES = "INVALIDATE_PATCH_COMPANIES";
export const REQUEST_DELETE_COMPANIES = "REQUEST_DELETE_COMPANIES";
export const RECEIVE_DELETE_COMPANIES = "RECEIVE_DELETE_COMPANIES";
export const INVALIDATE_DELETE_COMPANIES = "INVALIDATE_DELETE_COMPANIES";

//---------------------------------------------------------------------

export const REQUEST_GET_CHATBOTS = "REQUEST_GET_CHATBOTS";
export const RECEIVE_GET_CHATBOTS = "RECEIVE_GET_CHATBOTS";
export const INVALIDATE_GET_CHATBOTS = "INVALIDATE_GET_CHATBOTS";
export const REQUEST_GET_CHATBOTS_BY_COMPANY = "REQUEST_GET_CHATBOTS_BY_COMPANY";
export const RECEIVE_GET_CHATBOTS_BY_COMPANY = "RECEIVE_GET_CHATBOTS_BY_COMPANY";
export const INVALIDATE_GET_CHATBOTS_BY_COMPANY = "INVALIDATE_GET_CHATBOTS_BY_COMPANY";
export const REQUEST_GET_CHATBOTS_BY_USER = "REQUEST_GET_CHATBOTS_BY_USER";
export const RECEIVE_GET_CHATBOTS_BY_USER = "RECEIVE_GET_CHATBOTS_BY_USER";
export const INVALIDATE_GET_CHATBOTS_BY_USER = "INVALIDATE_GET_CHATBOTS_BY_USER";
export const REQUEST_POST_CHATBOTS = "REQUEST_POST_CHATBOTS";
export const RECEIVE_POST_CHATBOTS = "RECEIVE_POST_CHATBOTS";
export const INVALIDATE_POST_CHATBOTS = "INVALIDATE_POST_CHATBOTS";
export const REQUEST_PATCH_CHATBOTS = "REQUEST_PATCH_CHATBOTS";
export const RECEIVE_PATCH_CHATBOTS = "RECEIVE_PATCH_CHATBOTS";
export const INVALIDATE_PATCH_CHATBOTS = "INVALIDATE_PATCH_CHATBOTS";
export const REQUEST_DELETE_CHATBOTS = "REQUEST_DELETE_CHATBOTS";
export const RECEIVE_DELETE_CHATBOTS = "RECEIVE_DELETE_CHATBOTS";
export const INVALIDATE_DELETE_CHATBOTS = "INVALIDATE_DELETE_CHATBOTS";

//---------------------------------------------------------------------

export const REQUEST_GET_USERS = "REQUEST_GET_USERS";
export const RECEIVE_GET_USERS = "RECEIVE_GET_USERS";
export const INVALIDATE_GET_USERS = "INVALIDATE_GET_USERS";
export const REQUEST_GET_USERS_BY_COMPANY = "REQUEST_GET_USERS_BY_COMPANY";
export const RECEIVE_GET_USERS_BY_COMPANY = "RECEIVE_GET_USERS_BY_COMPANY";
export const INVALIDATE_GET_USERS_BY_COMPANY = "INVALIDATE_GET_USERS_BY_COMPANY";
export const REQUEST_POST_USERS = "REQUEST_POST_USERS";
export const RECEIVE_POST_USERS = "RECEIVE_POST_USERS";
export const INVALIDATE_POST_USERS = "INVALIDATE_POST_USERS";
export const REQUEST_PATCH_USERS = "REQUEST_PATCH_USERS";
export const RECEIVE_PATCH_USERS = "RECEIVE_PATCH_USERS";
export const INVALIDATE_PATCH_USERS = "INVALIDATE_PATCH_USERS";
export const REQUEST_DELETE_USERS = "REQUEST_DELETE_USERS";
export const RECEIVE_DELETE_USERS = "RECEIVE_DELETE_USERS";
export const INVALIDATE_DELETE_USERS = "INVALIDATE_DELETE_USERS";

//---------------------------------------------------------------------

export const REQUEST_GET_TESTS = "REQUEST_GET_TESTS";
export const RECEIVE_GET_TESTS = "RECEIVE_GET_TESTS";
export const INVALIDATE_GET_TESTS = "INVALIDATE_GET_TESTS";
export const REQUEST_GET_TESTS_BY_CHATBOT = "REQUEST_GET_TESTS_BY_CHATBOT";
export const RECEIVE_GET_TESTS_BY_CHATBOT = "RECEIVE_GET_TESTS_BY_CHATBOT";
export const INVALIDATE_GET_TESTS_BY_CHATBOT = "INVALIDATE_GET_TESTS_BY_CHATBOT";
export const REQUEST_POST_TESTS = "REQUEST_POST_TESTS";
export const RECEIVE_POST_TESTS = "RECEIVE_POST_TESTS";
export const INVALIDATE_POST_TESTS = "INVALIDATE_POST_TESTS";
export const REQUEST_PATCH_TESTS = "REQUEST_PATCH_TESTS";
export const RECEIVE_PATCH_TESTS = "RECEIVE_PATCH_TESTS";
export const INVALIDATE_PATCH_TESTS = "INVALIDATE_PATCH_TESTS";
export const REQUEST_DELETE_TESTS = "REQUEST_DELETE_TESTS";
export const RECEIVE_DELETE_TESTS = "RECEIVE_DELETE_TESTS";
export const INVALIDATE_DELETE_TESTS = "INVALIDATE_DELETE_TESTS";
