export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const RECEIVE_LOGIN = "RECEIVE_LOGIN";
export const INVALIDATE_LOGIN = "INVALIDATE_LOGIN";

export const REQUEST_TOKEN = "REQUEST_TOKEN";
export const RECEIVE_TOKEN = "RECEIVE_TOKEN";
export const INVALIDATE_TOKEN = "INVALIDATE_TOKEN";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//---------------------------------------------------------------------

export const REQUEST_GET_COMPANIES = "REQUEST_GET_COMPANIES";
export const RECEIVE_GET_COMPANIES = "RECEIVE_GET_COMPANIES";
export const INVALIDATE_GET_COMPANIES = "INVALIDATE_GET_COMPANIES";
export const REQUEST_POST_COMPANIES = "REQUEST_POST_COMPANIES";
export const RECEIVE_POST_COMPANIES = "RECEIVE_POST_COMPANIES";
export const INVALIDATE_POST_COMPANIES = "INVALIDATE_POST_COMPANIES";
export const REQUEST_PATCH_COMPANIES = "REQUEST_PATCH_COMPANIES";
export const RECEIVE_PATCH_COMPANIES = "RECEIVE_PATCH_COMPANIES";
export const INVALIDATE_PATCH_COMPANIES = "INVALIDATE_PATCH_COMPANIES";
export const REQUEST_DELETE_COMPANIES = "REQUEST_DELETE_COMPANIES";
export const RECEIVE_DELETE_COMPANIES = "RECEIVE_DELETE_COMPANIES";
export const INVALIDATE_DELETE_COMPANIES = "INVALIDATE_DELETE_COMPANIES";

//---------------------------------------------------------------------

export const REQUEST_GET_CHATBOTS = "REQUEST_GET_CHATBOTS";
export const RECEIVE_GET_CHATBOTS = "RECEIVE_GET_CHATBOTS";
export const INVALIDATE_GET_CHATBOTS = "INVALIDATE_GET_CHATBOTS";
export const REQUEST_GET_CHATBOTS_BY_COMPANY = "REQUEST_GET_CHATBOTS_BY_COMPANY";
export const RECEIVE_GET_CHATBOTS_BY_COMPANY = "RECEIVE_GET_CHATBOTS_BY_COMPANY";
export const INVALIDATE_GET_CHATBOTS_BY_COMPANY = "INVALIDATE_GET_CHATBOTS_BY_COMPANY";
export const REQUEST_GET_CHATBOTS_BY_USER = "REQUEST_GET_CHATBOTS_BY_USER";
export const RECEIVE_GET_CHATBOTS_BY_USER = "RECEIVE_GET_CHATBOTS_BY_USER";
export const INVALIDATE_GET_CHATBOTS_BY_USER = "INVALIDATE_GET_CHATBOTS_BY_USER";
export const REQUEST_POST_CHATBOTS = "REQUEST_POST_CHATBOTS";
export const RECEIVE_POST_CHATBOTS = "RECEIVE_POST_CHATBOTS";
export const INVALIDATE_POST_CHATBOTS = "INVALIDATE_POST_CHATBOTS";
export const REQUEST_PATCH_CHATBOTS = "REQUEST_PATCH_CHATBOTS";
export const RECEIVE_PATCH_CHATBOTS = "RECEIVE_PATCH_CHATBOTS";
export const INVALIDATE_PATCH_CHATBOTS = "INVALIDATE_PATCH_CHATBOTS";
export const REQUEST_DELETE_CHATBOTS = "REQUEST_DELETE_CHATBOTS";
export const RECEIVE_DELETE_CHATBOTS = "RECEIVE_DELETE_CHATBOTS";
export const INVALIDATE_DELETE_CHATBOTS = "INVALIDATE_DELETE_CHATBOTS";
export const REQUEST_START_CHATBOTS = "REQUEST_START_CHATBOTS";
export const RECEIVE_START_CHATBOTS = "RECEIVE_START_CHATBOTS";
export const INVALIDATE_START_CHATBOTS = "INVALIDATE_START_CHATBOTS";
export const REQUEST_STOP_CHATBOTS = "REQUEST_STOP_CHATBOTS";
export const RECEIVE_STOP_CHATBOTS = "RECEIVE_STOP_CHATBOTS";
export const INVALIDATE_STOP_CHATBOTS = "INVALIDATE_STOP_CHATBOTS";
export const REQUEST_LAUNCH_CHATBOTS = "REQUEST_LAUNCH_CHATBOTS";
export const RECEIVE_LAUNCH_CHATBOTS = "RECEIVE_LAUNCH_CHATBOTS";
export const INVALIDATE_LAUNCH_CHATBOTS = "INVALIDATE_LAUNCH_CHATBOTS";
export const REQUEST_TALK_CHATBOTS = "REQUEST_TALK_CHATBOTS";
export const RECEIVE_TALK_CHATBOTS = "RECEIVE_TALK_CHATBOTS";
export const INVALIDATE_TALK_CHATBOTS = "INVALIDATE_TALK_CHATBOTS";

//---------------------------------------------------------------------

export const REQUEST_GET_USERS = "REQUEST_GET_USERS";
export const RECEIVE_GET_USERS = "RECEIVE_GET_USERS";
export const INVALIDATE_GET_USERS = "INVALIDATE_GET_USERS";
export const REQUEST_GET_USERS_BY_COMPANY = "REQUEST_GET_USERS_BY_COMPANY";
export const RECEIVE_GET_USERS_BY_COMPANY = "RECEIVE_GET_USERS_BY_COMPANY";
export const INVALIDATE_GET_USERS_BY_COMPANY = "INVALIDATE_GET_USERS_BY_COMPANY";
export const REQUEST_POST_USERS = "REQUEST_POST_USERS";
export const RECEIVE_POST_USERS = "RECEIVE_POST_USERS";
export const INVALIDATE_POST_USERS = "INVALIDATE_POST_USERS";
export const REQUEST_PATCH_USERS = "REQUEST_PATCH_USERS";
export const RECEIVE_PATCH_USERS = "RECEIVE_PATCH_USERS";
export const INVALIDATE_PATCH_USERS = "INVALIDATE_PATCH_USERS";
export const REQUEST_DELETE_USERS = "REQUEST_DELETE_USERS";
export const RECEIVE_DELETE_USERS = "RECEIVE_DELETE_USERS";
export const INVALIDATE_DELETE_USERS = "INVALIDATE_DELETE_USERS";

//---------------------------------------------------------------------

export const REQUEST_GET_TESTS = "REQUEST_GET_TESTS";
export const RECEIVE_GET_TESTS = "RECEIVE_GET_TESTS";
export const INVALIDATE_GET_TESTS = "INVALIDATE_GET_TESTS";
export const REQUEST_GET_TESTS_BY_CHATBOT = "REQUEST_GET_TESTS_BY_CHATBOT";
export const RECEIVE_GET_TESTS_BY_CHATBOT = "RECEIVE_GET_TESTS_BY_CHATBOT";
export const INVALIDATE_GET_TESTS_BY_CHATBOT = "INVALIDATE_GET_TESTS_BY_CHATBOT";
export const REQUEST_POST_TESTS = "REQUEST_POST_TESTS";
export const RECEIVE_POST_TESTS = "RECEIVE_POST_TESTS";
export const INVALIDATE_POST_TESTS = "INVALIDATE_POST_TESTS";
export const REQUEST_PATCH_TESTS = "REQUEST_PATCH_TESTS";
export const RECEIVE_PATCH_TESTS = "RECEIVE_PATCH_TESTS";
export const INVALIDATE_PATCH_TESTS = "INVALIDATE_PATCH_TESTS";
export const REQUEST_DELETE_TESTS = "REQUEST_DELETE_TESTS";
export const RECEIVE_DELETE_TESTS = "RECEIVE_DELETE_TESTS";
export const INVALIDATE_DELETE_TESTS = "INVALIDATE_DELETE_TESTS";

//---------------------------------------------------------------------

export const REQUEST_GET_LOGS = "REQUEST_GET_LOGS";
export const RECEIVE_GET_LOGS = "RECEIVE_GET_LOGS";
export const INVALIDATE_GET_LOGS = "INVALIDATE_GET_LOGS";
export const REQUEST_GET_LOGS_BY_CHATBOT = "REQUEST_GET_LOGS_BY_CHATBOT";
export const RECEIVE_GET_LOGS_BY_CHATBOT = "RECEIVE_GET_LOGS_BY_CHATBOT";
export const INVALIDATE_GET_LOGS_BY_CHATBOT = "INVALIDATE_GET_LOGS_BY_CHATBOT";
export const REQUEST_POST_LOGS = "REQUEST_POST_LOGS";
export const RECEIVE_POST_LOGS = "RECEIVE_POST_LOGS";
export const INVALIDATE_POST_LOGS = "INVALIDATE_POST_LOGS";
export const REQUEST_PATCH_LOGS = "REQUEST_PATCH_LOGS";
export const RECEIVE_PATCH_LOGS = "RECEIVE_PATCH_LOGS";
export const INVALIDATE_PATCH_LOGS = "INVALIDATE_PATCH_LOGS";
export const REQUEST_DELETE_LOGS = "REQUEST_DELETE_LOGS";
export const RECEIVE_DELETE_LOGS = "RECEIVE_DELETE_LOGS";
export const INVALIDATE_DELETE_LOGS = "INVALIDATE_DELETE_LOGS";

//---------------------------------------------------------------------

export const INVALIDATE_GET_ASSERTIONS = "INVALIDATE_GET_ASSERTIONS";
export const REQUEST_GET_ASSERTIONS = "REQUEST_GET_ASSERTIONS";
export const RECEIVE_GET_ASSERTIONS = "RECEIVE_GET_ASSERTIONS";
export const INVALIDATE_GET_ASSERTIONS_BY_TEST = "INVALIDATE_GET_ASSERTIONS_BY_TEST";
export const REQUEST_GET_ASSERTIONS_BY_TEST = "REQUEST_GET_ASSERTIONS_BY_TEST";
export const RECEIVE_GET_ASSERTIONS_BY_TEST = "RECEIVE_GET_ASSERTIONS_BY_TEST";
export const INVALIDATE_POST_ASSERTIONS = "INVALIDATE_POST_ASSERTIONS";
export const REQUEST_POST_ASSERTIONS = "REQUEST_POST_ASSERTIONS";
export const RECEIVE_POST_ASSERTIONS = "RECEIVE_POST_ASSERTIONS";
export const INVALIDATE_PATCH_ASSERTIONS = "INVALIDATE_PATCH_ASSERTIONS";
export const REQUEST_PATCH_ASSERTIONS = "REQUEST_PATCH_ASSERTIONS";
export const RECEIVE_PATCH_ASSERTIONS = "RECEIVE_PATCH_ASSERTIONS";
export const INVALIDATE_DELETE_ASSERTIONS = "INVALIDATE_DELETE_ASSERTIONS";
export const REQUEST_DELETE_ASSERTIONS = "REQUEST_DELETE_ASSERTIONS";
export const RECEIVE_DELETE_ASSERTIONS = "RECEIVE_DELETE_ASSERTIONS";